console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
black = "#2E3440"
green = "#A3BE8C"
white = "#D8DEE9"
gray = "#84868b"
blue = "#81A1C1"
red = "#BF616A"
yellow = "#EBCB8B"
purple = "#B48EAD"
orange = "#f7931a"
darkblue = "#7292b2"

[secondary_prompt]
  # template = '❯ '
  template = '>> '
  foreground = 'p:green'
  background = 'transparent'

[transient_prompt]
  # template = ' '
  template ="$ "
  background = 'transparent'
  foreground_templates = [
    '{{if gt .Code 0}}p:red{{end}}',
    '{{if eq .Code 0}}p:green{{end}}'
  ]

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  ############################################################################
  ##### Python
  ############################################################################
  # If venv is active the icon is green else gray
   [[blocks.segments]]
      type = "python"
      style = "plain"
      template = " "
      foreground = "p:gray"
      background = "transparent"
      foreground_templates = [ "{{ if .Venv }}p:green{{ end }}" ]

    [blocks.segments.properties]
      display_mode = "files"
      fetch_virtual_env = true

  ############################################################################
  ##### Path
  ############################################################################
  [[blocks.segments]]
    type = "path"
    style = "powerline"
    template = '[ {{ .Path }} ]'
    foreground = 'p:gray'
    background = 'transparent'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  ############################################################################
  ##### Git
  ############################################################################
  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    template = '  {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{else }}≡{{ end }} <p:purple>{{ if gt .Behind 0 }}{{ end }}{{ if gt .Ahead 0 }}{{ end }}</>'
    foreground = 'p:red'
    background = 'transparent'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

############################################################################
##### Execution time of command 
############################################################################
[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

############################################################################
##### Main prompt
############################################################################
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    # template = ' '
    # \u001b[1m = bold on
    # \u001b[22m = bold off
    template = "\u001b[1m$\u001b[22m"
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}p:red{{end}}',
      '{{if eq .Code 0}}p:green{{end}}'
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
