name: Install

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Check winget version
        run: winget --version

      - name: Install dependencies
        shell: pwsh
        run: |
          ./setup.ps1
